---
name: POE-Component-WWW-DoingItWrongCom-RandImage
version: 0.02
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: |-
  non-blocking
  way to get URIs to random images from L<http://www.doingitwrong.com>
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Filter::Line: 1.192
  POE::Filter::Reference: 1.2187
  POE::Wheel::Run: 1.2179
  WWW::DoingItWrongCom::RandImage: 0.01
build_requires:
  Test::More: 0
provides:
  POE::Component::WWW::DoingItWrongCom::RandImage:
    file: lib/POE/Component/WWW/DoingItWrongCom/RandImage.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
